-- Phase 0 - warehouse, database, role, service user, Lightning schemas
-- Part of the Solstice CDP capstone build. Fictional brand, synthetic data.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE SOLSTICE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE SOLSTICE;
CREATE SCHEMA SOLSTICE.RAW;        -- synthetic source data
CREATE SCHEMA SOLSTICE.ANALYTICS;  -- dbt output, what Hightouch reads

CREATE ROLE SOLSTICE_HIGHTOUCH;
CREATE USER SOLSTICE_HT_SVC
  DEFAULT_ROLE = SOLSTICE_HIGHTOUCH
  DEFAULT_WAREHOUSE = SOLSTICE_WH
  DEFAULT_NAMESPACE = SOLSTICE   -- without this, a blank Database field in a
  TYPE = SERVICE;                -- destination's config becomes a failed sync
GRANT ROLE SOLSTICE_HIGHTOUCH TO USER SOLSTICE_HT_SVC;

GRANT USAGE ON WAREHOUSE SOLSTICE_WH TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON ALL TABLES IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON FUTURE TABLES IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON ALL VIEWS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;

-- Lightning sync engine needs write access to two schemas of its own.
CREATE SCHEMA IF NOT EXISTS SOLSTICE.HIGHTOUCH_AUDIT;
CREATE SCHEMA IF NOT EXISTS SOLSTICE.HIGHTOUCH_PLANNER;

-- REVOKE CURRENT GRANTS is doing real work here. The GRANT USAGE ON FUTURE
-- SCHEMAS above attached a USAGE grant to these two the instant they were
-- created, and Snowflake refuses to transfer ownership while a dependent grant
-- exists. This clears it in the same statement; ownership supersedes USAGE
-- anyway, so nothing is lost.
GRANT OWNERSHIP ON SCHEMA SOLSTICE.HIGHTOUCH_AUDIT
  TO ROLE SOLSTICE_HIGHTOUCH REVOKE CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA SOLSTICE.HIGHTOUCH_PLANNER
  TO ROLE SOLSTICE_HIGHTOUCH REVOKE CURRENT GRANTS;

-- Confirm: OWNERSHIP should sit with SOLSTICE_HIGHTOUCH.
SHOW GRANTS ON SCHEMA SOLSTICE.HIGHTOUCH_AUDIT;

-- ---------------------------------------------------------------------------
-- Cost guardrail. Free trial credits, so nothing is at stake here. The habit is
-- the point: a runaway sync schedule against a client account is a real invoice.
-- ---------------------------------------------------------------------------
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR SOLSTICE_GUARD
  WITH CREDIT_QUOTA = 50
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75  PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND
    ON 110 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE SOLSTICE_WH SET RESOURCE_MONITOR = SOLSTICE_GUARD;
