-- Phase 0 — warehouse, database, role, service user, Lightning schemas
-- Part of the Solstice CDP capstone build. Fictional brand, synthetic data.

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE SOLSTICE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE SOLSTICE;
CREATE SCHEMA SOLSTICE.RAW;        -- synthetic source data
CREATE SCHEMA SOLSTICE.ANALYTICS;  -- dbt output, what Hightouch reads

CREATE ROLE SOLSTICE_HIGHTOUCH;
CREATE USER SOLSTICE_HT_SVC
  DEFAULT_ROLE = SOLSTICE_HIGHTOUCH
  DEFAULT_WAREHOUSE = SOLSTICE_WH
  TYPE = SERVICE;
GRANT ROLE SOLSTICE_HIGHTOUCH TO USER SOLSTICE_HT_SVC;

GRANT USAGE ON WAREHOUSE SOLSTICE_WH TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON ALL SCHEMAS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON ALL TABLES IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON FUTURE TABLES IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON ALL VIEWS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;
GRANT SELECT ON FUTURE VIEWS IN DATABASE SOLSTICE TO ROLE SOLSTICE_HIGHTOUCH;

-- Lightning sync engine needs write access to two schemas of its own.
CREATE SCHEMA IF NOT EXISTS SOLSTICE.HIGHTOUCH_AUDIT;
CREATE SCHEMA IF NOT EXISTS SOLSTICE.HIGHTOUCH_PLANNER;
GRANT OWNERSHIP ON SCHEMA SOLSTICE.HIGHTOUCH_AUDIT TO ROLE SOLSTICE_HIGHTOUCH;
GRANT OWNERSHIP ON SCHEMA SOLSTICE.HIGHTOUCH_PLANNER TO ROLE SOLSTICE_HIGHTOUCH;
